import './comps.css';
import Card from './card';

function Container(
    IPv4, IPv6
){

    return (
        <div className="flex-container">
            <Card title="IPv4" desc = {IPv4} />
            <Card title="IPv6" desc = {IPv6} />
            <Card title="Test" desc = "TeEEEESSTasdfasdf" />
            <Card title="Test" desc = "TeEEEESST" />
            <Card title="Test" desc = "TeEEEESST" />
            <Card title="Testestsetset" desc = "TeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESST" />
            <Card title="Test" desc = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz" />
            <Card title="Test" desc = "TeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESSTTeEEEESST" />
            <Card title="Test" desc = "TeEEEESST" />
        </div>
    )

}

export default Container;